import 'package:flutter/material.dart';
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'amplifyconfiguration.dart';
import 'login_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  print('DEBUG: Widgets initialized');

  await _configureAmplify();

  print('DEBUG: Starting runApp');
  runApp(const MyApp());
}

Future<void> _configureAmplify() async {
  try {
    final auth = AmplifyAuthCognito();
    final api = AmplifyAPI();
    await Amplify.addPlugins([auth, api]);

    // Amplitfy configuration is generated by the CLI
    await Amplify.configure(amplifyconfig);
    print('DEBUG: Amplify configured successfully');
  } on AmplifyAlreadyConfiguredException {
    print('DEBUG: Amplify was already configured');
  } catch (e) {
    print('DEBUG: Amplify configuration failed: $e');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Cipher',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFFBEF263)),
        useMaterial3: true,
      ),
      home: const LoginPage(),
    );
  }
}
