import 'package:flutter/material.dart';
import 'package:amplify_api/amplify_api.dart';
import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
import 'package:amplify_flutter/amplify_flutter.dart';
import 'amplifyconfiguration.dart';
import 'login_page.dart';

import 'package:provider/provider.dart';
import 'providers/privacy_provider.dart';
import 'providers/call_provider.dart';
import 'providers/chat_notification_provider.dart';
import 'providers/settings_provider.dart';
import 'components/incoming_call_overlay.dart';
import 'components/chat_notification_banner.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'l10n/translations.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  print('DEBUG: Widgets initialized');

  await _configureAmplify();

  print('DEBUG: Starting runApp');
  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => PrivacyProvider()),
        ChangeNotifierProvider(create: (_) => CallProvider()),
        ChangeNotifierProvider(create: (_) => ChatNotificationProvider()),
        ChangeNotifierProvider(create: (_) => SettingsProvider()),
      ],
      child: const MyApp(),
    ),
  );
}

Future<void> _configureAmplify() async {
  try {
    final auth = AmplifyAuthCognito();
    final api = AmplifyAPI();
    await Amplify.addPlugins([auth, api]);

    // Amplitfy configuration is generated by the CLI
    await Amplify.configure(amplifyconfig);
    print('DEBUG: Amplify configured successfully');
  } on AmplifyAlreadyConfiguredException {
    print('DEBUG: Amplify was already configured');
  } catch (e) {
    print('DEBUG: Amplify configuration failed: $e');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  /// Global key so overlays rendered OUTSIDE the Navigator (e.g. in
  /// MaterialApp.builder) can still push routes onto the correct navigator.
  static final GlobalKey<NavigatorState> navigatorKey =
      GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return Consumer<SettingsProvider>(
      builder: (context, settings, _) {
        return MaterialApp(
          title: 'Cipher',
          debugShowCheckedModeBanner: false,
          themeMode: settings.themeMode,
          theme: ThemeData(
            colorScheme: ColorScheme.fromSeed(
              seedColor: const Color(0xFFBEF263),
              brightness: Brightness.light,
            ),
            useMaterial3: true,
          ),
          darkTheme: ThemeData(
            colorScheme: ColorScheme.fromSeed(
              seedColor: const Color(0xFFBEF263),
              brightness: Brightness.dark,
            ),
            scaffoldBackgroundColor: const Color(0xFF1B2210),
            useMaterial3: true,
          ),
          locale: settings.locale,
          supportedLocales: const [
            Locale('en', ''),
            Locale('es', ''), // Spanish
          ],
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          navigatorKey: MyApp.navigatorKey,
          home: const LoginPage(),
          builder: (context, child) {
            return Stack(
              children: [
                if (child != null) child,
                const IncomingCallOverlay(),
                const ChatNotificationBanner(),
              ],
            );
          },
        );
      },
    );
  }
}
